# Generated by Django 5.2 on 2025-04-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unibites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.FileField(default=None, null=True, upload_to='categoryIMGS/')),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
