# Generated by Django 5.2 on 2025-04-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unibites', '0003_alter_category_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[('1', 'active'), ('0', 'inactive')], default=1),
        ),
    ]
