# Generated by Django 5.2 on 2025-04-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unibites', '0004_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('1', 'active'), ('0', 'inactive')], default='1'),
        ),
    ]
