# Generated by Django 5.2 on 2025-04-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unibites', '0005_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('1', 'active'), ('0', 'inactive')], default='1')),
            ],
            options={
                'db_table': 'canteen',
            },
        ),
    ]
