# Generated by Django 5.2 on 2025-04-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unibites', '0006_canteen'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='image',
            field=models.FileField(default=None, null=True, upload_to='canteenIMGS/'),
        ),
    ]
