# Generated by Django 5.2 on 2025-04-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unibites', '0007_canteen_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteen',
            name='status',
            field=models.CharField(choices=[('1', 'active'), ('0', 'inactive')], default='0'),
        ),
    ]
