# Generated by Django 5.2 on 2025-04-14 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Unibites', '0008_alter_canteen_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canteen',
            options={'verbose_name': 'canteen', 'verbose_name_plural': 'canteens'},
        ),
    ]
