# Generated by Django 5.2 on 2025-04-19 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unibites', '0009_alter_canteen_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.FileField(default=None, null=True, upload_to='foodIMGS/')),
                ('price', models.FloatField()),
                ('discount', models.IntegerField()),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Unibites.canteen')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Unibites.category')),
            ],
            options={
                'verbose_name': 'foodItem',
                'verbose_name_plural': 'foodItems',
                'db_table': 'foodItem',
            },
        ),
    ]
