# Generated by Django 5.2 on 2025-04-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unibites', '0010_fooditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='discount',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
