# Generated by Django 5.2 on 2025-04-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unibites', '0011_alter_fooditem_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='discount',
            field=models.IntegerField(default='NA', null=True),
        ),
    ]
