# Generated by Django 5.2 on 2025-04-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unibites', '0012_alter_fooditem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='availability',
            field=models.CharField(choices=[('1', 'Available'), ('0', 'Not Available')], default='1', max_length=1),
        ),
    ]
