# Generated by Django 5.2 on 2025-04-30 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unibites', '0013_fooditem_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Unibites.canteen')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Unibites.fooditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Unibites.user')),
            ],
        ),
    ]
