# Generated by Django 5.2 on 2025-04-30 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Unibites', '0014_cartitem'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartitem',
            table='cartItem',
        ),
    ]
