# Generated by Django 5.2 on 2025-05-04 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unibites', '0015_alter_cartitem_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.FloatField()),
                ('mode', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('1', 'accept'), ('0', 'pending'), ('2', 'rejected')], default='0')),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Unibites.canteen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Unibites.user')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.FloatField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Unibites.fooditem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Unibites.order')),
            ],
            options={
                'verbose_name': 'orderDetails',
                'verbose_name_plural': 'orderDetails',
                'db_table': 'orderDetails',
            },
        ),
    ]
