# Generated by Django 5.2 on 2025-05-10 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unibites', '0017_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='canteen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Unibites.canteen'),
            preserve_default=False,
        ),
    ]
