from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('loginPage', loginPage, name='loginPage'),
    path('CanteenPage', CanteenPage, name='CanteenPage'),
    path('CanteenLogin', CanteenLogin, name='CanteenLogin'),
    path('canteenDash', canteenDash, name='canteenDash'),
    path("registerUser", registerUser, name="registerUser"),
    path("loginUser", loginUser, name="loginUser"),
    path("logoutUser", logoutUser, name="logoutUser"),
    path("logoutCanteen", logoutCanteen, name="logoutCanteen"),
    path("about", about, name="about"),
    path("contactUs", contactUs, name="contactUs"),
    path("addItemPage", addItemPage, name="addItemPage"),
    path("addFood", addFood, name="addFood"),
    path("manageFood", manageFood, name="manageFood"),
    path("Items", Items, name="Items"),
    path("changePassPage", changePassPage, name="changePassPage"),
    path("changeCanPWPage", changeCanPWPage, name="changeCanPWPage"),
    path("updateItem", updateItem, name="updateItem"),
    path("deleteItem/<int:id>", deleteItem, name="deleteItem"),
    path("changePass", changePass, name="changePass"),
    path("changeCanPW", changeCanPW, name="changeCanPW"),
    path("ViewCanteen", ViewCanteen, name="ViewCanteen"),
    path("mess", mess, name="mess"),
    path("Canteens", Canteens, name="Canteens"),
    path("editProfilePage", editProfilePage, name="editProfilePage"),
    path("editCanProfilePage", editCanProfilePage, name="editCanProfilePage"),
    path("openMenu/<int:id>", openMenu, name="openMenu"),
    path("updateProfile", updateProfile, name="updateProfile"),
    path("updateCanProfile", updateCanProfile, name="updateCanProfile"),
    path("AddToCartPage/", AddToCartPage, name="AddToCartPage"),
    path("UpdateCartQuantity/", UpdateCartQuantity, name="UpdateCartQuantity"),
    path("RemoveFromCart", RemoveFromCart, name="RemoveFromCart"),
    path("update_availability/<int:id>", update_availability, name="update_availability"),
    path("place_order", place_order, name="place_order"),
    path("myOrders", myOrders, name="myOrders"),
    path("CanOrders", CanOrders, name="CanOrders"),
    path("pendingOrder", pendingOrder, name="pendingOrder"),
    path("allPendingOrder", allPendingOrder, name="allPendingOrder"),
    path("changeOrderStatus", changeOrderStatus, name="changeOrderStatus"),
    path("searched_menu", searched_menu, name="searched_menu"),
    path("addReview", addReview, name="addReview"),
    path('forgotPassword', forgotPassword, name="forgotPassword"),

]
